# Generated by Django 4.0.4 on 2023-07-02 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='art_cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('art_img', models.ImageField(blank=True, upload_to='pic')),
            ],
        ),
        migrations.CreateModel(
            name='lag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(blank=True, upload_to='pic')),
            ],
        ),
        migrations.CreateModel(
            name='song_cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cat_img', models.ImageField(blank=True, upload_to='pic')),
            ],
        ),
        migrations.CreateModel(
            name='song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('m_name', models.CharField(max_length=200)),
                ('art', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='pic')),
                ('audio', models.FileField(upload_to='pic')),
                ('art_cat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='m.art_cat')),
                ('lag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='m.lag')),
                ('song_cat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='m.song_cat')),
            ],
        ),
    ]
